Pandas - DataFrame and Series

- Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. 
- It provides two primary data structures: Series and DataFrame.
- Series is a **one-dimensional array**-like object, while a DataFrame is a **two-dimensional**, size-mutable, and potentially heterogeneous tavular data structure with labeled axes (rows and columns)

In [2]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\teler\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\teler\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\teler\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\teler\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\teler\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

#### Series

In [ ]:
# A pandas Series is a one-dimensional array-like object that can hold various data types, such as integers, floats, strings, and more. It is similar to a column in a spreadsheet or a database table. Each element in a Series has an associated index, which allows for easy access and manipulation of the data.

data = [10, 20, 30, 40, 50]

# Creating a pandas Series from the data list
series = pd.Series(data)

print("Series: \n", series)
print(type(series))

Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.Series'>

In [10]:
# Creating a pandas Series from dictionary

data = {'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}

dict_series = pd.Series(data)

print(dict_series)
print(type(dict_series))

a    10
b    20
c    30
d    40
e    50
dtype: int64
<class 'pandas.Series'>

In [ ]:
# Creating a pandas Series with custom index

data = [10, 20, 30, 40, 50]

index = ['a', 'b', 'c', 'd', 'e']

pd.Series(data, index=index)

a    10
b    20
c    30
d    40
e    50
dtype: int64

##### DataFrame

In [ ]:
"""
DataFrame is a two-dimensional, size-mutable, and heterogeneous tabular data structure with labeled axes (rows and columns). It is similar to a spreadsheet or SQL table, and it can hold various data types, such as integers, floats, strings, and more. Each column in a DataFrame is a pandas Series, and each row can be accessed using its index.
"""

In [71]:
# Creating a pandas DataFrame from a dictionary of lists

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

# this will create a DataFrame with columns 'Name', 'Age', and 'City', and each row will represent a person with their corresponding information.
df = pd.DataFrame(data)

print("DataFrame from dictionary of lists: \n", df)

print(type(df))

DataFrame from dictionary of lists:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix
<class 'pandas.DataFrame'>

In [19]:
# Create a dataframe from a list of dictionaries

data = [
    {'Name': 'Alice', 'Age': 25, 'City': 'New York'},
    {'Name': 'Bob', 'Age': 30, 'City': 'Los Angeles'},
    {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'},
    {'Name': 'David', 'Age': 40, 'City': 'Houston'},
    {'Name': 'Eva', 'Age': 45, 'City': 'Phoenix'}
]


pf = pd.DataFrame(data)

print("DataFrame from list of dictionaries: \n", pf)

print(type(pf))

DataFrame from list of dictionaries:
       Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix
<class 'pandas.DataFrame'>

#### Read CSV Files

In [22]:
df = pd.read_csv('sales_data_sample.csv')

df.head() # Display the first 5 rows of the DataFrame

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [23]:
df.tail() # Display the last 5 rows of the DataFrame

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [27]:
## Accessing data from a DataFrame
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [32]:
print(df['Name']) # Accessing a single column (returns a Series)

print(type(df['Name'])) # Output: <class 'pandas.core.series.Series'>

0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: str
<class 'pandas.Series'>

In [33]:
df.loc[0] # Accessing a single row by index (returns a Series)

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [38]:
print(df.iloc[0]) # Accessing a single row by index (returns a Series)

Name       Alice
Age           25
City    New York
Name: 0, dtype: object

In [72]:
## Accessing a specific element

print(df.at[0, 'Name']) # Accessing a specific element by row and column indices
print(df.at[1, 'Name'])

print(df.at[2, "Age"])

Alice
Bob
35

In [73]:
## Accessing a specific element using 'iat'

print(df.iat[2, 2])

Chicago

In [74]:
## Data Manipulation with dataframes

df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [75]:
# Adding a new column 'Salary' to the DataFrame

df['Salary'] = [400000, 500000, 600000, 700000, 800000]
df

      Name  Age         City  Salary
0    Alice   25     New York  400000
1      Bob   30  Los Angeles  500000
2  Charlie   35      Chicago  600000
3    David   40      Houston  700000
4      Eva   45      Phoenix  800000

In [76]:
# Removing a column from the DataFrame
df.drop('Salary', axis=1, inplace=True) # Remove the 'Salary' column

# inplace=True modifies the original DataFrame in place, rather than returning a new DataFrame with the column removed.
# axis=1 specifies that we want to drop a column (axis=0 would be for dropping rows).

In [77]:
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eva   45      Phoenix

In [ ]:
## Add age to the column

# increase the 'Age' column by 1 for all rows in the DataFrame
df['Age'] = df['Age']+1

df

      Name  Age         City
0    Alice   26     New York
1      Bob   31  Los Angeles
2  Charlie   36      Chicago
3    David   41      Houston
4      Eva   46      Phoenix

In [81]:
# df.drop(0) # this is not a permanent operation, to make it permanent, we need to use inplace=True

df.drop(0, inplace=True)

In [82]:
df

      Name  Age         City
1      Bob   31  Los Angeles
2  Charlie   36      Chicago
3    David   41      Houston
4      Eva   46      Phoenix

In [85]:
# Display the data type of each column in the DataFrame
print("Data types: \n", df.dtypes)

# Describe the DataFrame
print("Statistical summary: \n", df.describe())

Data types:
 Name      str
Age     int64
City      str
dtype: object
Statistical summary:
              Age
count   4.000000
mean   38.500000
std     6.454972
min    31.000000
25%    34.750000
50%    38.500000
75%    42.250000
max    46.000000